from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1210, 892)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.groupBox.setFont(font)
        self.groupBox.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
        self.groupBox.setObjectName("groupBox")
        self.dreamName = QtWidgets.QLabel(parent=self.groupBox)
        self.dreamName.setGeometry(QtCore.QRect(30, 190, 351, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dreamName.setFont(font)
        self.dreamName.setObjectName("dreamName")
        self.progressBar = QtWidgets.QProgressBar(parent=self.groupBox)
        self.progressBar.setGeometry(QtCore.QRect(30, 220, 391, 31))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(30, 40, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.setDream = QtWidgets.QPushButton(parent=self.groupBox)
        self.setDream.setGeometry(QtCore.QRect(30, 260, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.setDream.setFont(font)
        self.setDream.setObjectName("setDream")
        self.piggy = QtWidgets.QLCDNumber(parent=self.groupBox)
        self.piggy.setGeometry(QtCore.QRect(30, 80, 191, 41))
        self.piggy.setObjectName("piggy")
        self.rub_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.rub_2.setGeometry(QtCore.QRect(240, 90, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rub_2.setFont(font)
        self.rub_2.setObjectName("rub_2")
        self.dreamInp = QtWidgets.QLineEdit(parent=self.groupBox)
        self.dreamInp.setGeometry(QtCore.QRect(310, 270, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.dreamInp.setFont(font)
        self.dreamInp.setObjectName("dreamInp")
        self.dreamCost = QtWidgets.QLineEdit(parent=self.groupBox)
        self.dreamCost.setGeometry(QtCore.QRect(310, 310, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.dreamCost.setFont(font)
        self.dreamCost.setObjectName("dreamCost")
        self.setDreamConf = QtWidgets.QPushButton(parent=self.groupBox)
        self.setDreamConf.setGeometry(QtCore.QRect(360, 350, 121, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.setDreamConf.setFont(font)
        self.setDreamConf.setObjectName("setDreamConf")
        self.breakPiggyBtn = QtWidgets.QPushButton(parent=self.groupBox)
        self.breakPiggyBtn.setGeometry(QtCore.QRect(30, 140, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.breakPiggyBtn.setFont(font)
        self.breakPiggyBtn.setObjectName("breakPiggyBtn")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(220, 270, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(250, 310, 47, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.rub_7 = QtWidgets.QLabel(parent=self.groupBox)
        self.rub_7.setGeometry(QtCore.QRect(510, 320, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rub_7.setFont(font)
        self.rub_7.setObjectName("rub_7")
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.sumInp = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.sumInp.setGeometry(QtCore.QRect(30, 120, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sumInp.setFont(font)
        self.sumInp.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
        self.sumInp.setText("")
        self.sumInp.setObjectName("sumInp")
        self.label = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(30, 50, 351, 51))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.addInpSum = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.addInpSum.setGeometry(QtCore.QRect(30, 180, 111, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.addInpSum.setFont(font)
        self.addInpSum.setObjectName("addInpSum")
        self.addOutSum = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.addOutSum.setGeometry(QtCore.QRect(170, 180, 111, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.addOutSum.setFont(font)
        self.addOutSum.setObjectName("addOutSum")
        self.rub_1 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.rub_1.setGeometry(QtCore.QRect(240, 130, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rub_1.setFont(font)
        self.rub_1.setObjectName("rub_1")
        self.gridLayout.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.sincePeriod = QtWidgets.QDateEdit(parent=self.groupBox_4)
        self.sincePeriod.setGeometry(QtCore.QRect(60, 90, 110, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sincePeriod.setFont(font)
        self.sincePeriod.setObjectName("sincePeriod")
        self.forPeriod = QtWidgets.QDateEdit(parent=self.groupBox_4)
        self.forPeriod.setGeometry(QtCore.QRect(210, 90, 110, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.forPeriod.setFont(font)
        self.forPeriod.setObjectName("forPeriod")
        self.label_7 = QtWidgets.QLabel(parent=self.groupBox_4)
        self.label_7.setGeometry(QtCore.QRect(20, 50, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=self.groupBox_4)
        self.label_8.setGeometry(QtCore.QRect(40, 80, 47, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(parent=self.groupBox_4)
        self.label_9.setGeometry(QtCore.QRect(180, 80, 47, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.periodConf = QtWidgets.QPushButton(parent=self.groupBox_4)
        self.periodConf.setGeometry(QtCore.QRect(350, 90, 101, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.periodConf.setFont(font)
        self.periodConf.setObjectName("periodConf")
        self.label_10 = QtWidgets.QLabel(parent=self.groupBox_4)
        self.label_10.setGeometry(QtCore.QRect(50, 140, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(parent=self.groupBox_4)
        self.label_11.setGeometry(QtCore.QRect(50, 180, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.LCDin = QtWidgets.QLCDNumber(parent=self.groupBox_4)
        self.LCDin.setGeometry(QtCore.QRect(160, 140, 111, 31))
        self.LCDin.setObjectName("LCDin")
        self.LCDout = QtWidgets.QLCDNumber(parent=self.groupBox_4)
        self.LCDout.setGeometry(QtCore.QRect(160, 180, 111, 31))
        self.LCDout.setObjectName("LCDout")
        self.rub_4 = QtWidgets.QLabel(parent=self.groupBox_4)
        self.rub_4.setGeometry(QtCore.QRect(290, 150, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rub_4.setFont(font)
        self.rub_4.setObjectName("rub_4")
        self.rub_5 = QtWidgets.QLabel(parent=self.groupBox_4)
        self.rub_5.setGeometry(QtCore.QRect(290, 190, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rub_5.setFont(font)
        self.rub_5.setObjectName("rub_5")
        self.label_14 = QtWidgets.QLabel(parent=self.groupBox_4)
        self.label_14.setGeometry(QtCore.QRect(50, 220, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.LCDpiggy = QtWidgets.QLCDNumber(parent=self.groupBox_4)
        self.LCDpiggy.setGeometry(QtCore.QRect(160, 220, 111, 31))
        self.LCDpiggy.setObjectName("LCDpiggy")
        self.rub_6 = QtWidgets.QLabel(parent=self.groupBox_4)
        self.rub_6.setGeometry(QtCore.QRect(290, 230, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rub_6.setFont(font)
        self.rub_6.setObjectName("rub_6")
        self.gridLayout.addWidget(self.groupBox_4, 1, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.mainAccount = QtWidgets.QLCDNumber(parent=self.groupBox_3)
        self.mainAccount.setGeometry(QtCore.QRect(30, 50, 231, 61))
        self.mainAccount.setObjectName("mainAccount")
        self.rub_3 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.rub_3.setGeometry(QtCore.QRect(280, 70, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.rub_3.setFont(font)
        self.rub_3.setObjectName("rub_3")
        self.fiillPiggy = QtWidgets.QPushButton(parent=self.groupBox_3)
        self.fiillPiggy.setGeometry(QtCore.QRect(30, 130, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.fiillPiggy.setFont(font)
        self.fiillPiggy.setObjectName("fiillPiggy")
        self.fillPiggySum = QtWidgets.QLineEdit(parent=self.groupBox_3)
        self.fillPiggySum.setGeometry(QtCore.QRect(220, 130, 113, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.fillPiggySum.setFont(font)
        self.fillPiggySum.setObjectName("fillPiggySum")
        self.fillPiggyConf = QtWidgets.QPushButton(parent=self.groupBox_3)
        self.fillPiggyConf.setGeometry(QtCore.QRect(260, 170, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fillPiggyConf.setFont(font)
        self.fillPiggyConf.setObjectName("fillPiggyConf")
        self.rub_8 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.rub_8.setGeometry(QtCore.QRect(350, 140, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rub_8.setFont(font)
        self.rub_8.setObjectName("rub_8")
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(150, 140, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.autoFill = QtWidgets.QCheckBox(parent=self.groupBox_3)
        self.autoFill.setGeometry(QtCore.QRect(40, 220, 411, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.autoFill.setFont(font)
        self.autoFill.setObjectName("autoFill")
        self.changeAutoFillBtn = QtWidgets.QPushButton(parent=self.groupBox_3)
        self.changeAutoFillBtn.setGeometry(QtCore.QRect(60, 260, 231, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.changeAutoFillBtn.setFont(font)
        self.changeAutoFillBtn.setObjectName("changeAutoFillBtn")
        self.gridLayout.addWidget(self.groupBox_3, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1210, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Money Calculator"))
        self.groupBox.setTitle(_translate("MainWindow", "Моя мечта"))
        self.dreamName.setText(_translate("MainWindow", "Мечта не задана"))
        self.label_4.setText(_translate("MainWindow", "В копилке:"))
        self.setDream.setText(_translate("MainWindow", "Установить/поменять\n"
"мечту"))
        self.rub_2.setText(_translate("MainWindow", "рублей"))
        self.setDreamConf.setText(_translate("MainWindow", "Установить мечту"))
        self.breakPiggyBtn.setText(_translate("MainWindow", "Разбить копилку и купить мечту"))
        self.label_2.setText(_translate("MainWindow", "Название:"))
        self.label_3.setText(_translate("MainWindow", "Цена:"))
        self.rub_7.setText(_translate("MainWindow", "рублей"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Доходы и расходы"))
        self.label.setText(_translate("MainWindow", "Введите сумму дохода/расхода:"))
        self.addInpSum.setText(_translate("MainWindow", "Добавить\n"
"доход"))
        self.addOutSum.setText(_translate("MainWindow", "Добавить\n"
"расход"))
        self.rub_1.setText(_translate("MainWindow", "рублей"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Анализ Финансов"))
        self.label_7.setText(_translate("MainWindow", "Выберите период:"))
        self.label_8.setText(_translate("MainWindow", "С"))
        self.label_9.setText(_translate("MainWindow", "по"))
        self.periodConf.setText(_translate("MainWindow", "Применить"))
        self.label_10.setText(_translate("MainWindow", "Доходов:"))
        self.label_11.setText(_translate("MainWindow", "Расходов:"))
        self.rub_4.setText(_translate("MainWindow", "рублей"))
        self.rub_5.setText(_translate("MainWindow", "рублей"))
        self.label_14.setText(_translate("MainWindow", "Отложено:"))
        self.rub_6.setText(_translate("MainWindow", "рублей"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Основной счёт"))
        self.rub_3.setText(_translate("MainWindow", "рублей"))
        self.fiillPiggy.setText(_translate("MainWindow", "Пополнить\n"
"копилку"))
        self.fillPiggyConf.setText(_translate("MainWindow", "Пополнить"))
        self.rub_8.setText(_translate("MainWindow", "рублей"))
        self.label_5.setText(_translate("MainWindow", "Сумма:"))
        self.autoFill.setText(_translate("MainWindow", "Автопополнение копилки (15% от суммы дохода)"))
        self.changeAutoFillBtn.setText(_translate("MainWindow", "Изменить сумму автопополнения"))
